version: 0.2

env:
  exported-variables:
    - k6_Cloud_Token

phases:
  pre_build:
    commands:
      - echo Pull grafana/k6 image..
      - docker pull grafana/k6
  build:
    commands:
      - echo Run performance test
      - docker run -i -e K6_CLOUD_TOKEN=${k6_Cloud_Token} grafana/k6 cloud - <specs_folder/cloud-test.js
  post_build:
    commands:
      - echo Performance test complete
