version: '3.4'

services:
  k6performacetests:
    image: k6performacetests
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
